name: desafio_flugo_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_database: ^12.1.1
  provider: ^6.1.5+1
  go_router: ^17.0.1
  intl: ^0.20.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  result_dart: ^2.1.1
  result_command: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true